import {
  Activity,
  BarChart3,
  Boxes,
  Braces,
  Brain,
  Bug,
  Clock,
  Cpu,
  Crown,
  Database,
  Divide,
  Equal,
  FileCode2,
  FileWarning,
  Filter,
  Flame,
  FlaskConical,
  Gauge,
  GitBranch,
  HardDrive,
  Infinity,
  KeyRound,
  Languages,
  Layers,
  Link2,
  ListOrdered,
  ListTodo,
  Lock,
  MousePointerClick,
  Network,
  RefreshCw,
  Repeat,
  RotateCcw,
  Scale,
  Server,
  ShieldAlert,
  ShieldCheck,
  Shuffle,
  Sigma,
  Sparkles,
  Split,
  Table,
  Table2,
  Target,
  Timer,
  Users,
  Variable,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Explicit icon registry instead of importing lucide's full dynamic map —
 * keeps the icon set tree-shakeable (Section 11 bundle budget). Content may
 * only use these kebab-case names (the authoring spec pins them); unknown
 * names fall back to a generic file icon so a miss is visible, never a crash.
 */
const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "bar-chart-3": BarChart3,
  boxes: Boxes,
  braces: Braces,
  brain: Brain,
  "brain-circuit": Brain,
  bug: Bug,
  clock: Clock,
  cpu: Cpu,
  crown: Crown,
  database: Database,
  divide: Divide,
  equal: Equal,
  "file-warning": FileWarning,
  filter: Filter,
  flame: Flame,
  "flask-conical": FlaskConical,
  gauge: Gauge,
  "git-branch": GitBranch,
  "hard-drive": HardDrive,
  infinity: Infinity,
  "key-round": KeyRound,
  languages: Languages,
  layers: Layers,
  "link-2": Link2,
  "list-ordered": ListOrdered,
  "list-todo": ListTodo,
  lock: Lock,
  "mouse-pointer-click": MousePointerClick,
  network: Network,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  "rotate-ccw": RotateCcw,
  scale: Scale,
  server: Server,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  shuffle: Shuffle,
  sigma: Sigma,
  sparkles: Sparkles,
  split: Split,
  table: Table,
  "table-2": Table2,
  target: Target,
  timer: Timer,
  users: Users,
  variable: Variable,
  zap: Zap,
};

export const REGISTERED_ICONS = Object.keys(ICONS);

export function ChallengeIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? FileCode2;
  return <Icon aria-hidden className={className} />;
}
